/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface Cloud {

  /** 
   * Determine the status of the nodes in the H2O cloud.
   *   @param skip_ticks skip_ticks
   *   @param _exclude_fields Comma-separated list of JSON field paths to exclude from the result, used like:
   *                          "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
   */
  @GET("/3/Cloud")
  Call<CloudV3> status(
    @Field("skip_ticks") boolean skip_ticks,
    @Field("_exclude_fields") String _exclude_fields
  );

  @GET("/3/Cloud")
  Call<CloudV3> status();

  /** 
   * Determine the status of the nodes in the H2O cloud.
   *   @param skip_ticks skip_ticks
   *   @param _exclude_fields Comma-separated list of JSON field paths to exclude from the result, used like:
   *                          "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
   */
  @HEAD("/3/Cloud")
  Call<CloudV3> head(
    @Field("skip_ticks") boolean skip_ticks,
    @Field("_exclude_fields") String _exclude_fields
  );

  @HEAD("/3/Cloud")
  Call<CloudV3> head();

}
