/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface ComputeGram {

  /** 
   * Get weighted gram matrix
   *   @param X source data
   *   @param W weight vector
   *   @param use_all_factor_levels use all factor levels when doing 1-hot encoding
   *   @param standardize standardize data
   *   @param skip_missing skip missing values
   */
  @GET("/3/ComputeGram")
  Call<GramV3> computeGram(
    @Field("X") String X,
    @Field("W") String W,
    @Field("use_all_factor_levels") boolean use_all_factor_levels,
    @Field("standardize") boolean standardize,
    @Field("skip_missing") boolean skip_missing
  );

  @GET("/3/ComputeGram")
  Call<GramV3> computeGram(@Field("X") String X);

}
