/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface DKV {

  /** 
   * Remove an arbitrary key from the H2O distributed K/V store.
   *   @param key Object to be removed.
   *   @param _exclude_fields Comma-separated list of JSON field paths to exclude from the result, used like:
   *                          "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
   */
  @DELETE("/3/DKV/{key}")
  Call<RemoveV3> remove(
    @Path("key") String key,
    @Field("_exclude_fields") String _exclude_fields
  );

  @DELETE("/3/DKV/{key}")
  Call<RemoveV3> remove(@Path("key") String key);

  /** 
   * Remove all keys from the H2O distributed K/V store.
   *   @param _exclude_fields Comma-separated list of JSON field paths to exclude from the result, used like:
   *                          "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
   */
  @DELETE("/3/DKV")
  Call<RemoveAllV3> removeAll(@Field("_exclude_fields") String _exclude_fields);

  @DELETE("/3/DKV")
  Call<RemoveAllV3> removeAll();

}
