/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface Endpoints {

  /** 
   * Returns the list of all REST API (v4) endpoints.
   *   @param __schema Url describing the schema of the current object.
   */
  @GET("/4/endpoints")
  Call<EndpointsListV4> listRoutes4(@Field("__schema") String __schema);

  @GET("/4/endpoints")
  Call<EndpointsListV4> listRoutes4();

}
