/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface GarbageCollect {

  /** 
   * Explicitly call System.gc().
   */
  @FormUrlEncoded
  @POST("/3/GarbageCollect")
  Call<GarbageCollectV3> gc();

}
