/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface GetGLMRegPath {

  /** 
   * Get full regularization path
   *   @param model source model
   *   @param lambdas Computed lambda values
   *   @param explained_deviance_train explained deviance on the training set
   *   @param explained_deviance_valid explained deviance on the validation set
   *   @param coefficients coefficients for all lambdas
   *   @param coefficients_std standardized coefficients for all lambdas
   *   @param coefficient_names coefficient names
   */
  @GET("/3/GetGLMRegPath")
  Call<GLMRegularizationPathV3> extractRegularizationPath(
    @Field("model") String model,
    @Field("lambdas") double[] lambdas,
    @Field("explained_deviance_train") double[] explained_deviance_train,
    @Field("explained_deviance_valid") double[] explained_deviance_valid,
    @Field("coefficients") double[][] coefficients,
    @Field("coefficients_std") double[][] coefficients_std,
    @Field("coefficient_names") String[] coefficient_names
  );

  @GET("/3/GetGLMRegPath")
  Call<GLMRegularizationPathV3> extractRegularizationPath(@Field("model") String model);

}
