/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface Grids {

  /** 
   * Return the specified grid search result.
   *   @param grid_id Grid id
   *   @param sort_by Model performance metric to sort by. Examples: logloss, residual_deviance, mse, rmse, mae,rmsle,
   *                  auc, r2, f1, recall, precision, accuracy, mcc, err, err_count, lift_top_group, max_per_class_error
   *   @param decreasing Specify whether sort order should be decreasing.
   *   @param model_ids Model IDs built by a grid search
   */
  @GET("/99/Grids/{grid_id}")
  Call<GridSchemaV99> fetch(
    @Path("grid_id") String grid_id,
    @Field("sort_by") String sort_by,
    @Field("decreasing") boolean decreasing,
    @Field("model_ids") String[] model_ids
  );

  @GET("/99/Grids/{grid_id}")
  Call<GridSchemaV99> fetch(@Path("grid_id") String grid_id);

  /** 
   * Return all grids from H2O distributed K/V store.
   */
  @GET("/99/Grids")
  Call<GridsV99> list();

}
