/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface ImportSQLTable {

  /** 
   * Import SQL table into an H2O Frame.
   *   @param connection_url connection_url
   *   @param table table
   *   @param select_query select_query
   *   @param username username
   *   @param password password
   *   @param columns columns
   *   @param optimize optimize
   *   @param _exclude_fields Comma-separated list of JSON field paths to exclude from the result, used like:
   *                          "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
   */
  @FormUrlEncoded
  @POST("/99/ImportSQLTable")
  Call<JobV3> importSQLTable(
    @Field("connection_url") String connection_url,
    @Field("table") String table,
    @Field("select_query") String select_query,
    @Field("username") String username,
    @Field("password") String password,
    @Field("columns") String columns,
    @Field("optimize") boolean optimize,
    @Field("_exclude_fields") String _exclude_fields
  );

  @FormUrlEncoded
  @POST("/99/ImportSQLTable")
  Call<JobV3> importSQLTable(
    @Field("connection_url") String connection_url,
    @Field("username") String username,
    @Field("password") String password
  );

}
