/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;
import okhttp3.ResponseBody;

public interface Logs {

  /** 
   * Get named log file for a node.
   *   @param nodeidx Identifier of the node to get logs from. It can be either node index starting from (0-based),
   *                  where -1 means current node, or IP and port.
   *   @param name Which specific log file to read from the log file directory. If left unspecified, the system chooses
   *               a default for you.
   *   @param _exclude_fields Comma-separated list of JSON field paths to exclude from the result, used like:
   *                          "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
   */
  @GET("/3/Logs/nodes/{nodeidx}/files/{name}")
  Call<LogsV3> fetch(
    @Path("nodeidx") String nodeidx,
    @Path("name") String name,
    @Query("_exclude_fields") String _exclude_fields
  );

  @GET("/3/Logs/nodes/{nodeidx}/files/{name}")
  Call<LogsV3> fetch(
    @Path("nodeidx") String nodeidx,
    @Path("name") String name
  );

}
