/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface MakeGLMModel {

  /** 
   * Make a new GLM model based on existing one
   *   @param model source model
   *   @param dest destination key
   *   @param names coefficient names
   *   @param beta new glm coefficients
   *   @param threshold decision threshold for label-generation
   */
  @FormUrlEncoded
  @POST("/3/MakeGLMModel")
  Call<GLMModelV3> make_model(
    @Field("model") String model,
    @Field("dest") String dest,
    @Field("names") String[] names,
    @Field("beta") double[] beta,
    @Field("threshold") float threshold
  );

  @FormUrlEncoded
  @POST("/3/MakeGLMModel")
  Call<GLMModelV3> make_model(
    @Field("model") String model,
    @Field("names") String[] names,
    @Field("beta") double[] beta
  );

}
