/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;
import okhttp3.ResponseBody;

public interface Rapids {

  /** 
   * Execute an Rapids AstRoot.
   *   @param ast A Rapids AstRoot expression
   *   @param session_id Session key
   *   @param id [DEPRECATED] Key name to assign Frame results
   *   @param _exclude_fields Comma-separated list of JSON field paths to exclude from the result, used like:
   *                          "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
   */
  @FormUrlEncoded
  @POST("/99/Rapids")
  Call<RapidsSchemaV3> rapidsExec(
    @Field("ast") String ast,
    @Field("session_id") String session_id,
    @Field("id") String id,
    @Field("_exclude_fields") String _exclude_fields
  );

  @FormUrlEncoded
  @POST("/99/Rapids")
  Call<RapidsSchemaV3> rapidsExec(@Field("ast") String ast);

  /** 
   * Produce help for Rapids AstRoot language.
   */
  @GET("/99/Rapids/help")
  Call<RapidsHelpV3> genHelp();

}
