/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface SplitFrame {

  /** 
   * Split an H2O Frame.
   *   @param key Job Key
   *   @param dataset Dataset
   *   @param ratios Split ratios - resulting number of split is ratios.length+1
   *   @param destination_frames Destination keys for each output frame split.
   */
  @FormUrlEncoded
  @POST("/3/SplitFrame")
  Call<SplitFrameV3> run(
    @Field("key") String key,
    @Field("dataset") String dataset,
    @Field("ratios") double[] ratios,
    @Field("destination_frames") String[] destination_frames
  );

  @FormUrlEncoded
  @POST("/3/SplitFrame")
  Call<SplitFrameV3> run();

}
