/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface Tabulate {

  /** 
   * Tabulate one column vs another.
   *   @param dataset Dataset
   *   @param predictor Predictor
   *   @param response Response
   *   @param weight Observation weights (optional)
   *   @param nbins_predictor Number of bins for predictor column
   *   @param nbins_response Number of bins for response column
   */
  @FormUrlEncoded
  @POST("/99/Tabulate")
  Call<TabulateV3> run(
    @Field("dataset") String dataset,
    @Field("predictor") String predictor,
    @Field("response") String response,
    @Field("weight") String weight,
    @Field("nbins_predictor") int nbins_predictor,
    @Field("nbins_response") int nbins_response
  );

  @FormUrlEncoded
  @POST("/99/Tabulate")
  Call<TabulateV3> run(
    @Field("dataset") String dataset,
    @Field("predictor") String predictor,
    @Field("response") String response
  );

}
