/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;
import okhttp3.ResponseBody;

public interface Tree {

  /** 
   * Obtain a traverseable representation of a specific tree
   *   @param model Key of the model the desired tree belongs to
   *   @param tree_number Index of the tree in the model.
   *   @param tree_class Name of the class of the tree. Ignored for regression and binomial.
   */
  @GET("/3/Tree")
  Call<TreeV3> getTree(
    @Query("model") String model,
    @Query("tree_number") int tree_number,
    @Query("tree_class") String tree_class
  );

  @GET("/3/Tree")
  Call<TreeV3> getTree(
    @Query("model") String model,
    @Query("tree_number") int tree_number
  );

}
