/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface UnlockKeys {

  /** 
   * Unlock all keys in the H2O distributed K/V store, to attempt to recover from a crash.
   *   @param _exclude_fields Comma-separated list of JSON field paths to exclude from the result, used like:
   *                          "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
   */
  @FormUrlEncoded
  @POST("/3/UnlockKeys")
  Call<UnlockKeysV3> unlock(@Field("_exclude_fields") String _exclude_fields);

  @FormUrlEncoded
  @POST("/3/UnlockKeys")
  Call<UnlockKeysV3> unlock();

}
