/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;

public interface Word2VecTransform {

  /** 
   * Transform words to vectors using a word2vec model
   *   @param model Source word2vec Model
   *   @param words_frame Words Frame
   *   @param aggregate_method Method of aggregating word-vector sequences into a single vector
   */
  @GET("/3/Word2VecTransform")
  Call<Word2VecTransformV3> transform(
    @Field("model") String model,
    @Field("words_frame") String words_frame,
    @Field("aggregate_method") Word2VecModelAggregateMethod aggregate_method
  );

  @GET("/3/Word2VecTransform")
  Call<Word2VecTransformV3> transform(
    @Field("model") String model,
    @Field("words_frame") String words_frame
  );

}
