/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.proxies.retrofit;

import water.bindings.pojos.*;
import retrofit2.*;
import retrofit2.http.*;
import okhttp3.ResponseBody;

public interface Word2VecSynonyms {

  /** 
   * Find synonyms using a word2vec model
   *   @param model Source word2vec Model
   *   @param word Target word to find synonyms for
   *   @param count Number of synonyms
   *   @param synonyms Synonymous words
   *   @param scores Similarity scores
   */
  @GET("/3/Word2VecSynonyms")
  Call<Word2VecSynonymsV3> findSynonyms(
    @Query("model") String model,
    @Query("word") String word,
    @Query("count") int count,
    @Query("synonyms") String[] synonyms,
    @Query("scores") double[] scores
  );

  @GET("/3/Word2VecSynonyms")
  Call<Word2VecSynonymsV3> findSynonyms(
    @Query("model") String model,
    @Query("word") String word,
    @Query("count") int count
  );

}
