/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class ColSpecifierV3 extends SchemaV3 {

    /**
     * Name of the column
     */
    @SerializedName("column_name")
    public String columnName;

    /**
     * List of fields which specify columns that must contain this column
     */
    @SerializedName("is_member_of_frames")
    public String[] isMemberOfFrames;

    /**
     * Public constructor
     */
    public ColSpecifierV3() {
        columnName = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
