/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class DataInfoFrameV3 extends SchemaV3 {

    /**
     * input frame
     */
    public FrameKeyV3 frame;

    /**
     * interactions
     */
    public String[] interactions;

    /**
     * use all factor levels
     */
    @SerializedName("use_all")
    public boolean useAll;

    /**
     * standardize
     */
    public boolean standardize;

    /**
     * interactions only returned
     */
    @SerializedName("interactions_only")
    public boolean interactionsOnly;

    /**
     * output frame
     */
    public FrameKeyV3 result;

    /**
     * Public constructor
     */
    public DataInfoFrameV3() {
        useAll = false;
        standardize = false;
        interactionsOnly = false;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
