/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class DecryptionSetupV3 extends RequestSchemaV3 {

    /**
     * Target key for the Decryption Tool
     */
    @SerializedName("decrypt_tool_id")
    public DecryptionToolKeyV3 decryptToolId;

    /**
     * Implementation of the Decryption Tool
     */
    @SerializedName("decrypt_impl")
    public String decryptImpl;

    /**
     * Location of Java Keystore
     */
    @SerializedName("keystore_id")
    public FrameKeyV3 keystoreId;

    /**
     * Keystore type
     */
    @SerializedName("keystore_type")
    public String keystoreType;

    /**
     * Key alias
     */
    @SerializedName("key_alias")
    public String keyAlias;

    /**
     * Key password
     */
    public String password;

    /**
     * Specification of the cipher (and padding)
     */
    @SerializedName("cipher_spec")
    public String cipherSpec;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Comma-separated list of JSON field paths to exclude from the result, used like:
    // "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
    public String _excludeFields;

    */

    /**
     * Public constructor
     */
    public DecryptionSetupV3() {
        decryptImpl = "water.parser.GenericDecryptionTool";
        keystoreType = "";
        keyAlias = "";
        password = "";
        cipherSpec = "";
        _excludeFields = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
