/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class FindV3 extends RequestSchemaV3 {

    /**
     * Frame to search
     */
    public FrameV3 key;

    /**
     * Column, or null for all
     */
    public String column;

    /**
     * Starting row for search
     */
    public long row;

    /**
     * Value to search for; leave blank for a search for missing values
     */
    public String match;

    /**
     * previous row with matching value, or -1
     */
    public long prev;

    /**
     * next row with matching value, or -1
     */
    public long next;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Comma-separated list of JSON field paths to exclude from the result, used like:
    // "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
    public String _excludeFields;

    */

    /**
     * Public constructor
     */
    public FindV3() {
        column = "";
        row = 0L;
        match = "";
        prev = 0L;
        next = 0L;
        _excludeFields = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
