/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class FramesV3 extends RequestSchemaV3 {

    /**
     * Name of Frame of interest
     */
    @SerializedName("frame_id")
    public FrameKeyV3 frameId;

    /**
     * Name of column of interest
     */
    public String column;

    /**
     * Row offset to return
     */
    @SerializedName("row_offset")
    public long rowOffset;

    /**
     * Number of rows to return
     */
    @SerializedName("row_count")
    public int rowCount;

    /**
     * Column offset to return
     */
    @SerializedName("column_offset")
    public int columnOffset;

    /**
     * Number of full columns to return. The columns between full_column_count and column_count will be returned without
     * the data
     */
    @SerializedName("full_column_count")
    public int fullColumnCount;

    /**
     * Number of columns to return
     */
    @SerializedName("column_count")
    public int columnCount;

    /**
     * Find and return compatible models?
     */
    @SerializedName("find_compatible_models")
    public boolean findCompatibleModels;

    /**
     * File output path
     */
    public String path;

    /**
     * Overwrite existing file
     */
    public boolean force;

    /**
     * Number of part files to use (1=single file,-1=automatic)
     */
    @SerializedName("num_parts")
    public int numParts;

    /**
     * Job for export file
     */
    public JobV3 job;

    /**
     * Frames
     */
    public FrameV3[] frames;

    /**
     * Compatible models
     */
    @SerializedName("compatible_models")
    public ModelSchemaV3[] compatibleModels;

    /**
     * Domains
     */
    public String[][] domain;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Comma-separated list of JSON field paths to exclude from the result, used like:
    // "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
    public String _excludeFields;

    */

    /**
     * Public constructor
     */
    public FramesV3() {
        column = "";
        rowOffset = 0L;
        rowCount = -1;
        columnOffset = 0;
        fullColumnCount = -1;
        columnCount = -1;
        findCompatibleModels = false;
        path = "";
        force = false;
        numParts = 1;
        _excludeFields = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
