/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class GLMRegularizationPathV3 extends SchemaV3 {

    /**
     * source model
     */
    public ModelKeyV3 model;

    /**
     * Computed lambda values
     */
    public double[] lambdas;

    /**
     * explained deviance on the training set
     */
    @SerializedName("explained_deviance_train")
    public double[] explainedDevianceTrain;

    /**
     * explained deviance on the validation set
     */
    @SerializedName("explained_deviance_valid")
    public double[] explainedDevianceValid;

    /**
     * coefficients for all lambdas
     */
    public double[][] coefficients;

    /**
     * standardized coefficients for all lambdas
     */
    @SerializedName("coefficients_std")
    public double[][] coefficientsStd;

    /**
     * coefficient names
     */
    @SerializedName("coefficient_names")
    public String[] coefficientNames;

    /**
     * Public constructor
     */
    public GLMRegularizationPathV3() {
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
