/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class GramV3 {

    /**
     * source data
     */
    @SerializedName("X")
    public FrameKeyV3 x;

    /**
     * weight vector
     */
    @SerializedName("W")
    public ColSpecifierV3 w;

    /**
     * use all factor levels when doing 1-hot encoding
     */
    @SerializedName("use_all_factor_levels")
    public boolean useAllFactorLevels;

    /**
     * standardize data
     */
    public boolean standardize;

    /**
     * skip missing values
     */
    @SerializedName("skip_missing")
    public boolean skipMissing;

    /**
     * Destination key for the resulting matrix.
     */
    @SerializedName("destination_frame")
    public FrameKeyV3 destinationFrame;

    /**
     * Public constructor
     */
    public GramV3() {
        useAllFactorLevels = false;
        standardize = false;
        skipMissing = false;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
