/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;
import java.util.Map;


public class GridSearchSchema extends SchemaV3 {

    /**
     * Basic model builder parameters.
     */
    public ModelParametersSchemaV3 parameters;

    /**
     * Grid search parameters.
     */
    @SerializedName("hyper_parameters")
    public Map<Object,Object> hyperParameters;

    /**
     * Destination id for this grid; auto-generated if not specified.
     */
    @SerializedName("grid_id")
    public GridKeyV3 gridId;

    /**
     * Hyperparameter search criteria, including strategy and early stopping directives.  If it is not given, exhaustive
     * Cartesian is used.
     */
    @SerializedName("search_criteria")
    public HyperSpaceSearchCriteriaV99 searchCriteria;

    /**
     * Number of all models generated by grid search.
     */
    @SerializedName("total_models")
    public int totalModels;

    /**
     * Job Key.
     */
    public JobV3 job;

    /**
     * Public constructor
     */
    public GridSearchSchema() {
        totalModels = 0;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
