/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class H2OModelBuilderErrorV3 extends H2OErrorV3 {

    /**
     * Model builder parameters.
     */
    public ModelParametersSchemaV3 parameters;

    /**
     * Parameter validation messages
     */
    public ValidationMessageV3[] messages;

    /**
     * Count of parameter validation errors
     */
    @SerializedName("error_count")
    public int errorCount;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Milliseconds since the epoch for the time that this H2OError instance was created.  Generally this is a short
    // time since the underlying error ocurred.
    public long timestamp;

    // Error url
    public String errorUrl;

    // Message intended for the end user (a data scientist).
    public String msg;

    // Potentially more detailed message intended for a developer (e.g. a front end engineer or someone designing a
    // language binding).
    public String devMsg;

    // HTTP status code for this error.
    public int httpStatus;

    // Any values that are relevant to reporting or handling this error.  Examples are a key name if the error is on a
    // key, or a field name and object name if it's on a specific field.
    public Map<String,Object> values;

    // Exception type, if any.
    public String exceptionType;

    // Raw exception message, if any.
    public String exceptionMsg;

    // Stacktrace, if any.
    public String[] stacktrace;

    */

    /**
     * Public constructor
     */
    public H2OModelBuilderErrorV3() {
        errorCount = 0;
        timestamp = 0L;
        errorUrl = "";
        msg = "";
        devMsg = "";
        httpStatus = 0;
        exceptionType = "";
        exceptionMsg = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
