/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class InteractionV3 extends RequestSchemaV3 {

    /**
     * destination key
     */
    public FrameKeyV3 dest;

    /**
     * Input data frame
     */
    @SerializedName("source_frame")
    public FrameKeyV3 sourceFrame;

    /**
     * Factor columns
     */
    @SerializedName("factor_columns")
    public String[] factorColumns;

    /**
     * Whether to create pairwise quadratic interactions between factors (otherwise create one higher-order
     * interaction). Only applicable if there are 3 or more factors.
     */
    public boolean pairwise;

    /**
     * Max. number of factor levels in pair-wise interaction terms (if enforced, one extra catch-all factor will be
     * made)
     */
    @SerializedName("max_factors")
    public int maxFactors;

    /**
     * Min. occurrence threshold for factor levels in pair-wise interaction terms
     */
    @SerializedName("min_occurrence")
    public int minOccurrence;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Comma-separated list of JSON field paths to exclude from the result, used like:
    // "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
    public String _excludeFields;

    */

    /**
     * Public constructor
     */
    public InteractionV3() {
        pairwise = false;
        maxFactors = 100;
        minOccurrence = 1;
        _excludeFields = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
