/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class IOEvent extends EventV3 {

    /**
     * flavor of the recorded io (ice/hdfs/...)
     */
    @SerializedName("io_flavor")
    public String ioFlavor;

    /**
     * node where this io event happened
     */
    public String node;

    /**
     * data info
     */
    public String data;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Time when the event was recorded. Format is hh:mm:ss:ms
    public String date;

    // Time in nanos
    public long nanos;

    // type of recorded event
    public TimelineEventEventTypeV3 type;

    */

    /**
     * Public constructor
     */
    public IOEvent() {
        ioFlavor = "unknown";
        node = "unknown";
        data = "unknown";
        date = "23:59:59:999";
        nanos = -1L;
        type = TimelineEventEventTypeV3.io;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
