/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class IoStatsEntry extends SchemaV3 {

    /**
     * Back end type
     */
    public String backend;

    /**
     * Number of store events
     */
    @SerializedName("store_count")
    public long storeCount;

    /**
     * Cumulative stored bytes
     */
    @SerializedName("store_bytes")
    public long storeBytes;

    /**
     * Number of delete events
     */
    @SerializedName("delete_count")
    public long deleteCount;

    /**
     * Number of load events
     */
    @SerializedName("load_count")
    public long loadCount;

    /**
     * Cumulative loaded bytes
     */
    @SerializedName("load_bytes")
    public long loadBytes;

    /**
     * Public constructor
     */
    public IoStatsEntry() {
        backend = "";
        storeCount = 0L;
        storeBytes = 0L;
        deleteCount = 0L;
        loadCount = 0L;
        loadBytes = 0L;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
