/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class JobV3 extends SchemaV3 {

    /**
     * Job Key
     */
    public JobKeyV3 key;

    /**
     * Job description
     */
    public String description;

    /**
     * job status
     */
    public String status;

    /**
     * progress, from 0 to 1
     */
    public float progress;

    /**
     * current progress status description
     */
    @SerializedName("progress_msg")
    public String progressMsg;

    /**
     * Start time
     */
    @SerializedName("start_time")
    public long startTime;

    /**
     * Runtime in milliseconds
     */
    public long msec;

    /**
     * destination key
     */
    public KeyV3 dest;

    /**
     * exception
     */
    public String[] warnings;

    /**
     * exception
     */
    public String exception;

    /**
     * stacktrace
     */
    public String stacktrace;

    /**
     * ready for view
     */
    @SerializedName("ready_for_view")
    public boolean readyForView;

    /**
     * Public constructor
     */
    public JobV3() {
        description = "";
        status = "";
        progress = 0.0f;
        progressMsg = "";
        startTime = 0L;
        msec = 0L;
        exception = "";
        stacktrace = "";
        readyForView = false;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
