/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class LeaderboardV99 {

    /**
     * Identifier for models that should be grouped together in the leaderboard
     */
    @SerializedName("project_name")
    public String projectName;

    /**
     * List of models for this leaderboard, sorted by metric so that the best is first
     */
    public ModelKeyV3[] models;

    /**
     * Frame for this leaderboard
     */
    @SerializedName("leaderboard_frame")
    public FrameKeyV3[] leaderboardFrame;

    /**
     * Checksum for the Frame for this leaderboard
     */
    @SerializedName("leaderboard_frame_checksum")
    public long leaderboardFrameChecksum;

    /**
     * Sort metrics for the models in this leaderboard, in the same order as the models
     */
    @SerializedName("sort_metrics")
    public double[] sortMetrics;

    /**
     * Metric used to sort this leaderboard
     */
    @SerializedName("sort_metric")
    public String sortMetric;

    /**
     * Metric direction used in the sort
     */
    @SerializedName("sort_decreasing")
    public boolean sortDecreasing;

    /**
     * Public constructor
     */
    public LeaderboardV99() {
        projectName = "<default>";
        leaderboardFrameChecksum = 0L;
        sortMetric = "";
        sortDecreasing = false;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
