/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class LogsV3 extends RequestSchemaV3 {

    /**
     * Identifier of the node to get logs from. It can be either node index starting from (0-based), where -1 means
     * current node, or IP and port.
     */
    public String nodeidx;

    /**
     * Which specific log file to read from the log file directory. If left unspecified, the system chooses a default
     * for you.
     */
    public String name;

    /**
     * Content of log file
     */
    public String log;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Comma-separated list of JSON field paths to exclude from the result, used like:
    // "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
    public String _excludeFields;

    */

    /**
     * Public constructor
     */
    public LogsV3() {
        nodeidx = "";
        name = "";
        log = "";
        _excludeFields = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
