/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class MakeGLMModelV3 extends SchemaV3 {

    /**
     * source model
     */
    public ModelKeyV3 model;

    /**
     * destination key
     */
    public ModelKeyV3 dest;

    /**
     * coefficient names
     */
    public String[] names;

    /**
     * new glm coefficients
     */
    public double[] beta;

    /**
     * decision threshold for label-generation
     */
    public float threshold;

    /**
     * Public constructor
     */
    public MakeGLMModelV3() {
        threshold = 0.5f;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
