/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class ModelExportV3 extends RequestSchemaV3 {

    /**
     * Name of Model of interest
     */
    @SerializedName("model_id")
    public ModelKeyV3 modelId;

    /**
     * Destination file (hdfs, s3, local)
     */
    public String dir;

    /**
     * Overwrite destination file in case it exists or throw exception if set to false.
     */
    public boolean force;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Comma-separated list of JSON field paths to exclude from the result, used like:
    // "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
    public String _excludeFields;

    */

    /**
     * Public constructor
     */
    public ModelExportV3() {
        dir = "";
        force = true;
        _excludeFields = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
