/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class ModelBuilderV3 extends SchemaV3 {

    /**
     * Model builder parameters.
     */
    public ModelParametersSchemaV3 parameters;

    /**
     * Info, warning and error messages; NOTE: can be appended to while the Job is running
     */
    public ValidationMessageV3[] messages;

    /**
     * Count of error messages
     */
    @SerializedName("error_count")
    public int errorCount;

    /**
     * Public constructor
     */
    public ModelBuilderV3() {
        errorCount = 0;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
