/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

public enum ModelParametersFoldAssignmentScheme {
    AUTO,
    Modulo,
    Random,
    Stratified,
}
