/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class ModelMetricsMakerSchemaV3 extends SchemaV3 {

    /**
     * Predictions Frame.
     */
    @SerializedName("predictions_frame")
    public String predictionsFrame;

    /**
     * Actuals Frame.
     */
    @SerializedName("actuals_frame")
    public String actualsFrame;

    /**
     * Domain (for classification).
     */
    public String[] domain;

    /**
     * Distribution (for regression).
     */
    public GenmodelutilsDistributionFamily distribution;

    /**
     * Model Metrics.
     */
    @SerializedName("model_metrics")
    public ModelMetricsBaseV3 modelMetrics;

    /**
     * Public constructor
     */
    public ModelMetricsMakerSchemaV3() {
        predictionsFrame = "";
        actualsFrame = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
