/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class ModelSchemaBaseV3 extends SchemaV3 {

    /**
     * Model key
     */
    @SerializedName("model_id")
    public ModelKeyV3 modelId;

    /**
     * The algo name for this Model.
     */
    public String algo;

    /**
     * The pretty algo name for this Model (e.g., Generalized Linear Model, rather than GLM).
     */
    @SerializedName("algo_full_name")
    public String algoFullName;

    /**
     * The response column name for this Model (if applicable). Is null otherwise.
     */
    @SerializedName("response_column_name")
    public String responseColumnName;

    /**
     * The Model's training frame key
     */
    @SerializedName("data_frame")
    public FrameKeyV3 dataFrame;

    /**
     * Timestamp for when this model was completed
     */
    public long timestamp;

    /**
     * Indicator, whether export to POJO is available
     */
    @SerializedName("have_pojo")
    public boolean havePojo;

    /**
     * Indicator, whether export to MOJO is available
     */
    @SerializedName("have_mojo")
    public boolean haveMojo;

    /**
     * Public constructor
     */
    public ModelSchemaBaseV3() {
        algo = "";
        algoFullName = "";
        responseColumnName = "";
        timestamp = 0L;
        havePojo = false;
        haveMojo = false;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
