/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class NetworkTestV3 extends RequestSchemaV3 {

    /**
     * Collective broadcast/reduce times in microseconds (for each message size)
     */
    @SerializedName("microseconds_collective")
    public double[] microsecondsCollective;

    /**
     * Collective bandwidths in Bytes/sec (for each message size, for each node)
     */
    @SerializedName("bandwidths_collective")
    public double[] bandwidthsCollective;

    /**
     * Round-trip times in microseconds (for each message size, for each node)
     */
    public double[][] microseconds;

    /**
     * Bi-directional bandwidths in Bytes/sec (for each message size, for each node)
     */
    public double[][] bandwidths;

    /**
     * Nodes
     */
    public String[] nodes;

    /**
     * NetworkTestResults
     */
    public TwoDimTableV3 table;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Comma-separated list of JSON field paths to exclude from the result, used like:
    // "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
    public String _excludeFields;

    */

    /**
     * Public constructor
     */
    public NetworkTestV3() {
        _excludeFields = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
