/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class NodePersistentStorageV3 extends RequestSchemaV3 {

    /**
     * Category name
     */
    public String category;

    /**
     * Key name
     */
    public String name;

    /**
     * Value
     */
    public String value;

    /**
     * Configured
     */
    public boolean configured;

    /**
     * Exists
     */
    public boolean exists;

    /**
     * List of entries
     */
    public NodePersistentStorageEntryV3[] entries;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Comma-separated list of JSON field paths to exclude from the result, used like:
    // "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
    public String _excludeFields;

    */

    /**
     * Public constructor
     */
    public NodePersistentStorageV3() {
        category = "";
        name = "";
        value = "";
        configured = false;
        exists = false;
        _excludeFields = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
