/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class NodePersistentStorageEntryV3 extends SchemaV3 {

    /**
     * Category name
     */
    public String category;

    /**
     * Key name
     */
    public String name;

    /**
     * Size in bytes of value
     */
    public long size;

    /**
     * Epoch time in milliseconds of when the value was written
     */
    @SerializedName("timestamp_millis")
    public long timestampMillis;

    /**
     * Public constructor
     */
    public NodePersistentStorageEntryV3() {
        category = "";
        name = "";
        size = 0L;
        timestampMillis = 0L;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
