/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class ParseSetupV3 extends RequestSchemaV3 {

    /**
     * Source frames
     */
    @SerializedName("source_frames")
    public FrameKeyV3[] sourceFrames;

    /**
     * Parser type
     */
    @SerializedName("parse_type")
    public ApiParseTypeValuesProvider parseType;

    /**
     * Field separator
     */
    public byte separator;

    /**
     * Single quotes
     */
    @SerializedName("single_quotes")
    public boolean singleQuotes;

    /**
     * Check header: 0 means guess, +1 means 1st line is header not data, -1 means 1st line is data not header
     */
    @SerializedName("check_header")
    public int checkHeader;

    /**
     * Column names
     */
    @SerializedName("column_names")
    public String[] columnNames;

    /**
     * Value types for columns
     */
    @SerializedName("column_types")
    public String[] columnTypes;

    /**
     * NA strings for columns
     */
    @SerializedName("na_strings")
    public String[][] naStrings;

    /**
     * Regex for names of columns to return
     */
    @SerializedName("column_name_filter")
    public String columnNameFilter;

    /**
     * Column offset to return
     */
    @SerializedName("column_offset")
    public int columnOffset;

    /**
     * Number of columns to return
     */
    @SerializedName("column_count")
    public int columnCount;

    /**
     * Suggested name
     */
    @SerializedName("destination_frame")
    public String destinationFrame;

    /**
     * Number of header lines found
     */
    @SerializedName("header_lines")
    public long headerLines;

    /**
     * Number of columns
     */
    @SerializedName("number_columns")
    public int numberColumns;

    /**
     * Sample data
     */
    public String[][] data;

    /**
     * Warnings
     */
    public String[] warnings;

    /**
     * Size of individual parse tasks
     */
    @SerializedName("chunk_size")
    public int chunkSize;

    /**
     * Total number of columns we would return with no column pagination
     */
    @SerializedName("total_filtered_column_count")
    public int totalFilteredColumnCount;

    /**
     * Key-reference to an initialized instance of a Decryption Tool
     */
    @SerializedName("decrypt_tool")
    public DecryptionToolKeyV3 decryptTool;


    /*------------------------------------------------------------------------------------------------------------------
    //                                                  INHERITED
    //------------------------------------------------------------------------------------------------------------------

    // Comma-separated list of JSON field paths to exclude from the result, used like:
    // "/3/Frames?_exclude_fields=frames/frame_id/URL,__meta"
    public String _excludeFields;

    */

    /**
     * Public constructor
     */
    public ParseSetupV3() {
        parseType = ApiParseTypeValuesProvider.GUESS;
        separator = 0;
        singleQuotes = false;
        checkHeader = 0;
        columnNameFilter = "";
        columnOffset = 0;
        columnCount = 0;
        destinationFrame = "";
        headerLines = 0L;
        numberColumns = 0;
        chunkSize = 4194304;
        totalFilteredColumnCount = 0;
        _excludeFields = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
