/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class RouteV3 extends SchemaV3 {

    /**

     */
    @SerializedName("http_method")
    public String httpMethod;

    /**

     */
    @SerializedName("url_pattern")
    public String urlPattern;

    /**

     */
    public String summary;

    /**

     */
    @SerializedName("api_name")
    public String apiName;

    /**

     */
    @SerializedName("handler_class")
    public String handlerClass;

    /**

     */
    @SerializedName("handler_method")
    public String handlerMethod;

    /**

     */
    @SerializedName("input_schema")
    public String inputSchema;

    /**

     */
    @SerializedName("output_schema")
    public String outputSchema;

    /**

     */
    @SerializedName("path_params")
    public String[] pathParams;

    /**

     */
    public String markdown;

    /**
     * Public constructor
     */
    public RouteV3() {
        httpMethod = "";
        urlPattern = "";
        summary = "";
        apiName = "";
        handlerClass = "";
        handlerMethod = "";
        inputSchema = "";
        outputSchema = "";
        markdown = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
