/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class SchemaMetadataV3 extends SchemaV3 {

    /**
     * Version number of the Schema.
     */
    public int version;

    /**
     * Simple name of the Schema. NOTE: the schema_names form a single namespace.
     */
    public String name;

    /**
     * [DEPRECATED] This field is always the same as name.
     */
    public String label;

    /**
     * Simple name of the superclass of the Schema.  NOTE: the schema_names form a single namespace.
     */
    public String superclass;

    /**
     * Simple name of H2O type that this Schema represents. Must not be changed after creation (treat as final).
     */
    public String type;

    /**
     * All the public fields of the schema
     */
    public FieldMetadataV3[] fields;

    /**
     * Documentation for the schema in Markdown format with GitHub extensions
     */
    public String markdown;

    /**
     * Public constructor
     */
    public SchemaMetadataV3() {
        version = 0;
        name = "";
        label = "";
        superclass = "";
        type = "";
        fields = new FieldMetadataV3[]{};
        markdown = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
