/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class SplitFrameV3 extends SchemaV3 {

    /**
     * Job Key
     */
    public JobKeyV3 key;

    /**
     * Dataset
     */
    public FrameKeyV3 dataset;

    /**
     * Split ratios - resulting number of split is ratios.length+1
     */
    public double[] ratios;

    /**
     * Destination keys for each output frame split.
     */
    @SerializedName("destination_frames")
    public FrameKeyV3[] destinationFrames;

    /**
     * Public constructor
     */
    public SplitFrameV3() {
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
