/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class TabulateV3 extends SchemaV3 {

    /**
     * Dataset
     */
    public FrameKeyV3 dataset;

    /**
     * Predictor
     */
    public ColSpecifierV3 predictor;

    /**
     * Response
     */
    public ColSpecifierV3 response;

    /**
     * Observation weights (optional)
     */
    public ColSpecifierV3 weight;

    /**
     * Number of bins for predictor column
     */
    @SerializedName("nbins_predictor")
    public int nbinsPredictor;

    /**
     * Number of bins for response column
     */
    @SerializedName("nbins_response")
    public int nbinsResponse;

    /**
     * Counts table
     */
    @SerializedName("count_table")
    public TwoDimTableV3 countTable;

    /**
     * Response table
     */
    @SerializedName("response_table")
    public TwoDimTableV3 responseTable;

    /**
     * Public constructor
     */
    public TabulateV3() {
        nbinsPredictor = 20;
        nbinsResponse = 10;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
