/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class TreeStatsV3 extends SchemaV3 {

    /**
     * minDepth
     */
    @SerializedName("min_depth")
    public int minDepth;

    /**
     * maxDepth
     */
    @SerializedName("max_depth")
    public int maxDepth;

    /**
     * meanDepth
     */
    @SerializedName("mean_depth")
    public float meanDepth;

    /**
     * minLeaves
     */
    @SerializedName("min_leaves")
    public int minLeaves;

    /**
     * maxLeaves
     */
    @SerializedName("max_leaves")
    public int maxLeaves;

    /**
     * meanLeaves
     */
    @SerializedName("mean_leaves")
    public float meanLeaves;

    /**
     * Public constructor
     */
    public TreeStatsV3() {
        minDepth = 0;
        maxDepth = 0;
        meanDepth = 0.0f;
        minLeaves = 0;
        maxLeaves = 0;
        meanLeaves = 0.0f;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
