/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class TwoDimTableV3 extends SchemaV3 {

    /**
     * Table Name
     */
    public String name;

    /**
     * Table Description
     */
    public String description;

    /**
     * Column Specification
     */
    public ColumnSpecsBase[] columns;

    /**
     * Number of Rows
     */
    public int rowcount;

    /**
     * Table Data (col-major)
     */
    public Object[][] data;

    /**
     * Public constructor
     */
    public TwoDimTableV3() {
        name = "";
        description = "";
        rowcount = 0;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
