/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.GsonBuilder;
import com.google.gson.annotations.*;


public class ValidationMessageV3 extends SchemaV3 {

    /**
     * Type of validation message (ERROR, WARN, INFO, HIDE)
     */
    @SerializedName("message_type")
    public String messageType;

    /**
     * Field to which the message applies
     */
    @SerializedName("field_name")
    public String fieldName;

    /**
     * Message text
     */
    public String message;

    /**
     * Public constructor
     */
    public ValidationMessageV3() {
        messageType = "";
        fieldName = "";
        message = "";
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new GsonBuilder().serializeSpecialFloatingPointValues().create().toJson(this);
    }

}
