/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class Word2VecSynonymsV3 extends SchemaV3 {

    /**
     * Source word2vec Model
     */
    public ModelKeyV3 model;

    /**
     * Target word to find synonyms for
     */
    public String word;

    /**
     * Number of synonyms
     */
    public int count;

    /**
     * Synonymous words
     */
    public String[] synonyms;

    /**
     * Similarity scores
     */
    public double[] scores;

    /**
     * Public constructor
     */
    public Word2VecSynonymsV3() {
        word = "";
        count = 0;
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
