/*
 * This file is auto-generated by h2o-3/h2o-bindings/bin/gen_java.py
 * Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details)
 */
package water.bindings.pojos;

import com.google.gson.Gson;
import com.google.gson.annotations.*;


public class Word2VecTransformV3 extends SchemaV3 {

    /**
     * Source word2vec Model
     */
    public ModelKeyV3 model;

    /**
     * Words Frame
     */
    @SerializedName("words_frame")
    public FrameKeyV3 wordsFrame;

    /**
     * Method of aggregating word-vector sequences into a single vector
     */
    @SerializedName("aggregate_method")
    public Word2VecModelAggregateMethod aggregateMethod;

    /**
     * Word Vectors Frame
     */
    @SerializedName("vectors_frame")
    public FrameKeyV3 vectorsFrame;

    /**
     * Public constructor
     */
    public Word2VecTransformV3() {
    }

    /**
     * Return the contents of this object as a JSON String.
     */
    @Override
    public String toString() {
        return new Gson().toJson(this);
    }

}
